# Generated by Django 4.2.1 on 2026-03-14 14:14

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Berries', 'Ягоди'), ('Fruits', 'Фрукти'), ('Grains', 'Зернові'), ('Vegetables', 'Овочі'), ('Forage', 'Кормові')], default='Vegetables', max_length=50, verbose_name='Категорія')),
                ('name', models.CharField(max_length=50, verbose_name='Назва культури')),
                ('image', models.ImageField(blank=True, upload_to='crops', verbose_name='Зображення')),
                ('archived', models.BooleanField(default=False, verbose_name='Заархівовано')),
                ('min_humidity', models.FloatField(help_text='в %', validators=[django.core.validators.MinValueValidator(0.0, message='Не може бути менше 0.'), django.core.validators.MaxValueValidator(100.0, message='Не може бути більше 100.')], verbose_name='Мін. вологість')),
                ('max_humidity', models.FloatField(help_text='в %', validators=[django.core.validators.MinValueValidator(0.0, message='Не може бути менше 0.'), django.core.validators.MaxValueValidator(100.0, message='Не може бути більше 100.')], verbose_name='Макс. вологість')),
                ('min_temperature', models.FloatField(help_text='°C', verbose_name='Мін. температура')),
                ('max_temperature', models.FloatField(help_text='°C', verbose_name='Макс. температура')),
                ('min_ph', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0, message='Не може бути менше 0.'), django.core.validators.MaxValueValidator(14.0, message='pH не може бути більше 14.')], verbose_name='Мін. pH')),
                ('max_ph', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0, message='Не може бути менше 0.'), django.core.validators.MaxValueValidator(14.0, message='pH не може бути більше 14.')], verbose_name='Макс. pH')),
                ('min_nitrogen', models.FloatField(help_text='мг/кг', validators=[django.core.validators.MinValueValidator(0.0, message='Не може бути менше 0.')], verbose_name='Мін. вміст азоту')),
                ('max_nitrogen', models.FloatField(help_text='мг/кг', validators=[django.core.validators.MinValueValidator(0.0, message='Не може бути менше 0.')], verbose_name='Макс. вміст азоту')),
            ],
            options={
                'verbose_name': 'Культура',
                'verbose_name_plural': 'Культури',
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Назва сектору')),
                ('archived', models.BooleanField(default=False, verbose_name='Заархівовано')),
                ('x_start', models.FloatField(help_text='Зміщення зліва у %', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Позиція X')),
                ('y_start', models.FloatField(help_text='Зміщення зверху у %', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Позиція Y')),
                ('width', models.FloatField(help_text='Ширина сектора у %', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Ширина')),
                ('height', models.FloatField(help_text='Висота сектора у %', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Висота')),
                ('crop', models.ForeignKey(blank=True, limit_choices_to={'archived': False}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sectors', to='farm_monitoring.crop', verbose_name='Посіяна культура')),
            ],
            options={
                'verbose_name': 'Ділянка',
                'verbose_name_plural': 'Ділянки',
            },
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('TEMP', 'Температура'), ('HUM', 'Вологість'), ('PH', 'Кислотність'), ('NIT', 'Азот')], max_length=5, verbose_name='Тип сенсора')),
                ('serial_number', models.CharField(help_text='Format: SF-type-number', max_length=20, verbose_name='Серійний номер сенсора')),
                ('offset_x', models.FloatField(help_text='у %', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Розташування за Х')),
                ('offset_y', models.FloatField(help_text='у %', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Розташування за Y')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активований')),
                ('archived', models.BooleanField(default=False, verbose_name='Заархівовано')),
                ('sector', models.ForeignKey(blank=True, limit_choices_to={'archived': False}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sensors', to='farm_monitoring.sector', verbose_name='Сектор')),
            ],
            options={
                'verbose_name': 'Сенсор',
                'verbose_name_plural': 'Сенсори',
            },
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='farm_monitoring.sensor')),
            ],
            options={
                'verbose_name': 'Показник',
                'verbose_name_plural': 'Показники',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('ADMIN', 'Адміністратор'), ('EMPLOYEE', 'Співробітник')], default='EMPLOYEE', max_length=10, verbose_name='Роль')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Користувач',
                'verbose_name_plural': 'Користувачі',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddConstraint(
            model_name='sensor',
            constraint=models.UniqueConstraint(condition=models.Q(('archived', False)), fields=('serial_number',), name='unique_active_sensor_serial'),
        ),
        migrations.AddIndex(
            model_name='measurement',
            index=models.Index(fields=['sensor', 'timestamp'], name='farm_monito_sensor__bb7442_idx'),
        ),
    ]
