# Generated by Django 4.2.1 on 2026-01-15 11:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Назва культури')),
                ('min_humidity', models.FloatField(help_text='в %', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Мін. вологість')),
                ('max_humidity', models.FloatField(help_text='в %', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Макс. вологість')),
                ('min_temperature', models.FloatField(help_text='°C', verbose_name='Мін. температура')),
                ('max_temperature', models.FloatField(help_text='°C', verbose_name='Макс. температура')),
                ('min_ph', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(14.0)], verbose_name='Мін. pH')),
                ('max_ph', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(14.0)], verbose_name='Макс. pH')),
                ('min_nitrogen', models.FloatField(help_text='мг/кг', validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Мін. вміст азоту')),
                ('max_nitrogen', models.FloatField(help_text='мг/кг', validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Макс. вміст азоту')),
            ],
            options={
                'verbose_name': 'Культура',
                'verbose_name_plural': 'Культури',
            },
        ),
    ]
