# Generated by Django 4.2.1 on 2026-01-26 17:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farm_monitoring', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Назва сектору')),
                ('x_start', models.FloatField(help_text='у %', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('y_start', models.FloatField(help_text='у %', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('height', models.FloatField(help_text='у %', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('width', models.FloatField(help_text='у %', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('crop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='farm_monitoring.crop')),
            ],
            options={
                'verbose_name': 'Ділянка',
                'verbose_name_plural': 'Ділянки',
            },
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('TEMP', 'Температура'), ('HUM', 'Вологість'), ('PH', 'Кислотність'), ('NIT', 'Азот')], max_length=5)),
                ('serial_number', models.CharField(help_text='Format: SF-type-number', max_length=20, unique=True)),
                ('offset_x', models.FloatField(help_text='у %', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('offset_y', models.FloatField(help_text='у %', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('is_active', models.BooleanField(default=True)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to='farm_monitoring.sector')),
            ],
            options={
                'verbose_name': ('Сенсор',),
                'verbose_name_plural': 'Сенсори',
            },
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='farm_monitoring.sensor')),
            ],
            options={
                'verbose_name': 'Показник',
                'verbose_name_plural': 'Показники',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['sensor', 'timestamp'], name='farm_monito_sensor__bb7442_idx')],
            },
        ),
    ]
