# Generated by Django 4.2.1 on 2026-02-05 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_monitoring', '0002_sector_sensor_measurement'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='image',
            field=models.ImageField(blank=True, upload_to='crops'),
        ),
    ]
