# Generated by Django 4.2.1 on 2026-02-11 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_monitoring', '0003_crop_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='category',
            field=models.CharField(choices=[('Berries', 'Ягоди'), ('Fruits', 'Фруктові'), ('Cereals', 'Зернові'), ('Vegetables', 'Овочеві'), ('Forage', 'Кормові')], default='Vegetables', max_length=20),
        ),
        migrations.AlterField(
            model_name='crop',
            name='image',
            field=models.ImageField(blank=True, upload_to='crops', verbose_name='Зображення'),
        ),
    ]
