# Generated by Django 4.2.1 on 2026-02-12 20:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_monitoring', '0004_crop_category_alter_crop_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='category',
            field=models.CharField(choices=[('Ягоди', 'Ягоди'), ('Фрукти', 'Фрукти'), ('Зернові', 'Зернові'), ('Овочі', 'Овочі'), ('Кормові', 'Кормові')], default='Овочі', max_length=50, verbose_name='Категорія'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='max_nitrogen',
            field=models.FloatField(help_text='мг/кг', validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Макс. вміст нітратів'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='min_nitrogen',
            field=models.FloatField(help_text='мг/кг', validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Мін. вміст нітратів'),
        ),
    ]
