# Generated by Django 4.2.1 on 2026-02-18 09:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_monitoring', '0005_alter_crop_category_alter_crop_max_nitrogen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='crop',
            name='max_humidity',
            field=models.FloatField(help_text='в %', validators=[django.core.validators.MinValueValidator(0.0, message='Не може бути менше 0.'), django.core.validators.MaxValueValidator(100.0, message='Не може бути більше 100.')], verbose_name='Макс. вологість'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='max_nitrogen',
            field=models.FloatField(help_text='мг/кг', validators=[django.core.validators.MinValueValidator(0.0, message='Не може бути менше 0.')], verbose_name='Макс. вміст нітратів'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='max_ph',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0, message='Не може бути менше 0.'), django.core.validators.MaxValueValidator(14.0, message='pH не може бути більше 14.')], verbose_name='Макс. pH'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='min_humidity',
            field=models.FloatField(help_text='в %', validators=[django.core.validators.MinValueValidator(0.0, message='Не може бути менше 0.'), django.core.validators.MaxValueValidator(100.0, message='Не може бути більше 100.')], verbose_name='Мін. вологість'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='min_nitrogen',
            field=models.FloatField(help_text='мг/кг', validators=[django.core.validators.MinValueValidator(0.0, message='Не може бути менше 0.')], verbose_name='Мін. вміст нітратів'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='min_ph',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0, message='Не може бути менше 0.'), django.core.validators.MaxValueValidator(14.0, message='pH не може бути більше 14.')], verbose_name='Мін. pH'),
        ),
    ]
