# Generated by Django 4.2.1 on 2026-02-21 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_monitoring', '0006_crop_archived_alter_crop_max_humidity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='archived',
            field=models.BooleanField(default=False, verbose_name='Заархівовано'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='category',
            field=models.CharField(choices=[('Berries', 'Ягоди'), ('Fruits', 'Фрукти'), ('Grains', 'Зернові'), ('Vegetables', 'Овочі'), ('Forage', 'Кормові')], default='Vegetables', max_length=50, verbose_name='Категорія'),
        ),
    ]
