# Generated by Django 4.2.1 on 2026-02-23 09:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farm_monitoring', '0007_alter_crop_archived_alter_crop_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='archived',
            field=models.BooleanField(default=False, verbose_name='Заархівовано'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активований'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='offset_x',
            field=models.FloatField(help_text='у %', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Розташування за Х'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='offset_y',
            field=models.FloatField(help_text='у %', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Розташування за Y'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to='farm_monitoring.sector', verbose_name='Сектор'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='serial_number',
            field=models.CharField(help_text='Format: SF-type-number', max_length=20, unique=True, verbose_name='Серійний номер сенсора'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='type',
            field=models.CharField(choices=[('TEMP', 'Температура'), ('HUM', 'Вологість'), ('PH', 'Кислотність'), ('NIT', 'Нітрати')], max_length=5, verbose_name='Тип сенсора'),
        ),
    ]
