# Generated by Django 4.2.1 on 2026-02-24 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_monitoring', '0008_sensor_archived_alter_sensor_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='serial_number',
            field=models.CharField(help_text='Format: SF-type-number', max_length=20, verbose_name='Серійний номер сенсора'),
        ),
        migrations.AddConstraint(
            model_name='sensor',
            constraint=models.UniqueConstraint(condition=models.Q(('archived', False)), fields=('serial_number',), name='unique_active_sensor_serial'),
        ),
    ]
