# Generated by Django 4.2.1 on 2026-02-24 19:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_monitoring', '0009_alter_sensor_serial_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='max_nitrogen',
            field=models.FloatField(help_text='мг/кг', validators=[django.core.validators.MinValueValidator(0.0, message='Не може бути менше 0.')], verbose_name='Макс. вміст азоту'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='min_nitrogen',
            field=models.FloatField(help_text='мг/кг', validators=[django.core.validators.MinValueValidator(0.0, message='Не може бути менше 0.')], verbose_name='Мін. вміст азоту'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='type',
            field=models.CharField(choices=[('TEMP', 'Температура'), ('HUM', 'Вологість'), ('PH', 'Кислотність'), ('NIT', 'Азот')], max_length=5, verbose_name='Тип сенсора'),
        ),
    ]
