# Generated by Django 4.2.1 on 2026-02-27 19:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farm_monitoring', '0010_alter_crop_max_nitrogen_alter_crop_min_nitrogen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sector',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='Заархівовано'),
        ),
        migrations.AlterField(
            model_name='sector',
            name='crop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sectors', to='farm_monitoring.crop', verbose_name='Посіяна культура'),
        ),
        migrations.AlterField(
            model_name='sector',
            name='height',
            field=models.FloatField(help_text='Висота сектора у %', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Висота'),
        ),
        migrations.AlterField(
            model_name='sector',
            name='width',
            field=models.FloatField(help_text='Ширина сектора у %', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Ширина'),
        ),
        migrations.AlterField(
            model_name='sector',
            name='x_start',
            field=models.FloatField(help_text='Зміщення зліва у %', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Позиція X'),
        ),
        migrations.AlterField(
            model_name='sector',
            name='y_start',
            field=models.FloatField(help_text='Зміщення зверху у %', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Позиція Y'),
        ),
    ]
