# Generated by Django 4.2.1 on 2026-03-01 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farm_monitoring', '0011_sector_is_archived_alter_sector_crop_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sector',
            old_name='is_archived',
            new_name='archived',
        ),
    ]
