# Generated by Django 4.2.1 on 2026-03-04 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farm_monitoring', '0012_rename_is_archived_sector_archived'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sensor',
            options={'verbose_name': 'Сенсор', 'verbose_name_plural': 'Сенсори'},
        ),
        migrations.AlterField(
            model_name='sector',
            name='crop',
            field=models.ForeignKey(blank=True, limit_choices_to={'archived': False}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sectors', to='farm_monitoring.crop', verbose_name='Посіяна культура'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='sector',
            field=models.ForeignKey(blank=True, limit_choices_to={'archived': False}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sensors', to='farm_monitoring.sector', verbose_name='Сектор'),
        ),
    ]
